// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqq3jYlggRY28S6L1WgQJJbFafVcLRmok',
    appId: '1:31081041098:web:4c5b17633976c2d3957833',
    messagingSenderId: '31081041098',
    projectId: 'kitticure-app',
    authDomain: 'kitticure-app.firebaseapp.com',
    databaseURL: 'https://kitticure-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitticure-app.appspot.com',
    measurementId: 'G-W4R8NY7E0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIINuRPATuRd3JS4NvWvDhePAgxKX81as',
    appId: '1:31081041098:android:e255ab323cdef277957833',
    messagingSenderId: '31081041098',
    projectId: 'kitticure-app',
    databaseURL: 'https://kitticure-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitticure-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6yf_mfZfVsVnIe7ITjwB9OvkeZGpn6M',
    appId: '1:31081041098:ios:03122c6e883637d4957833',
    messagingSenderId: '31081041098',
    projectId: 'kitticure-app',
    databaseURL: 'https://kitticure-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitticure-app.appspot.com',
    iosClientId: '31081041098-bfeol200bc6pihrid9vfgq15cco0n1t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitticure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6yf_mfZfVsVnIe7ITjwB9OvkeZGpn6M',
    appId: '1:31081041098:ios:03122c6e883637d4957833',
    messagingSenderId: '31081041098',
    projectId: 'kitticure-app',
    databaseURL: 'https://kitticure-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitticure-app.appspot.com',
    iosClientId: '31081041098-bfeol200bc6pihrid9vfgq15cco0n1t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitticure',
  );
}
